---
kind: pipeline
name: x86_64

environment:
  DOCKER_BUILDKIT: 1

steps:
  - name: slack notification on start
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      template: >
        {{repo.owner}}/{{repo.name}} ({{build.branch}}) x86_64 build #{{build.number}} start: {{build.link}}
    when:
      branch:
        - master
        - develop
      event:
        - push
        - tag

  - name: build latest image
    image: plugins/docker
    settings:
      repo: mohemohe/ubuntu
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master
      event:
        - push

  - name: slack notification on complete
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      template: >
        {{#success build.status}}
           {{repo.owner}}/{{repo.name}} ({{build.branch}}) x86_64 build #{{build.number}} succeeded: {{build.link}}
        {{else}}
        {{repo.owner}}/{{repo.name}} ({{build.branch}}) x86_64 build #{{build.number}} failed: {{build.link}}
        {{/success}}
    when:
      branch:
        - master
        - develop
      event:
        - push
        - tag
      status:
        - success
        - failure

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

environment:
  DOCKER_BUILDKIT: 1

steps:
  - name: slack notification on start
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      template: >
        {{repo.owner}}/{{repo.name}} ({{build.branch}}) arm64 build #{{build.number}} start: {{build.link}}
    when:
      branch:
        - master
        - develop
      event:
        - push
        - tag

  - name: build latest image
    image: plugins/docker
    settings:
      repo: mohemohe/ubuntu
      tag: latest-arm64
      build_args:
        - S6_OVERLAY_ARCH=aarch64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master
      event:
        - push

  - name: slack notification on complete
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      template: >
        {{#success build.status}}
           {{repo.owner}}/{{repo.name}} ({{build.branch}}) arm64 build #{{build.number}} succeeded: {{build.link}}
        {{else}}
        {{repo.owner}}/{{repo.name}} ({{build.branch}}) arm64 build #{{build.number}} failed: {{build.link}}
        {{/success}}
    when:
      branch:
        - master
        - develop
      event:
        - push
        - tag
      status:
        - success
        - failure
