name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 15 * * 0"

jobs:
  build_amd64:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: mohemohe/ubuntu:latest

  build_arm64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: mohemohe
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: mohemohe/ubuntu:latest-arm64
          build-args: |-
            S6_OVERLAY_ARCH=aarch64
